export const RCLONE_CONFIG_DEFAULTS = {
    'MultiThreadCutoff': '64M',
    'MultiThreadStreams': 8,
    'MultiThreadChunkSize': '8M',
    'UseListR': true,
    'UseServerModTime': true,
    'BufferSize': '32M',
    'Transfers': 8,
    'Checkers': 16,
}

export const RCLONE_VFS_DEFAULTS = {
    'ChunkSize': '4M',
    'ChunkStreams': 16,
}

export const RCLONE_CONF_REGEX = /[\/\\]rclone\.conf$/
export const DOUBLE_BACKSLASH_REGEX = /\\\\/g

export const SUPPORTED_BACKENDS = [
    'azureblob',
    'azurefiles',
    'b2',
    'box',
    'drive',
    'dropbox',
    'sftp',
    's3',
    'ftp',
    'gcs',
    'protondrive',
    'webdav',
    'onedrive',
    'http',
    'storj',
    'gphotos',
    'netstorage',
    'oos',
    'swift',
    'compress',
    'union',
    'hasher',
    'combine',
    'chunker',
    'memory',
    'crypt',
    'alias',
    'cache',
    'local',
    'hdfs',
    'cloudinary',
    'doi',
    'filelu',
    'filescom',
    'imagekit',
    'internetarchive',
    'koofr',
    'linkbox',
    'mega',
    'opendrive',
    'pixeldrain',
    'seafile',
    'sia',
    'smb',
    'ulozto',
    'gofile',
    'qingstor',
    'filefabric',
    'quatrix',
    'sugarsync',
    'hidrive',
    'jottacloud',
    'mailru',
    'pcloud',
    'pikpak',
    'premiumizeme',
    'putio',
    'sharefile',
    'yandex',
    'zoho',
]
